services:
    shopping_cart.security.login_form_authenticator:
        class: ShoppingCartBundle\Security\LoginFormAuthenticator
        autowire: true
        calls:
            - [createAuthenticatedToken, ['@security.user.provider.in_memory.user', '@?']]
            - [getUser, ['@?', '@security.user.provider.ldap']]
            - [checkCredentials, ['@?', '@security.user.provider.in_memory.user']]

    shopping_cart.doctrine.hash_password_listener:
        class: ShoppingCartBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    ShoppingCartBundle\Service\ReviewServiceInterface:
        alias: 'ShoppingCartBundle\Service\ReviewService'
        public: false

    ShoppingCartBundle\Service\PromotionServiceInterface:
        alias: 'ShoppingCartBundle\Service\PromotionService'
        public: false

    ShoppingCartBundle\Service\CartServiceInterface:
        alias: 'ShoppingCartBundle\Service\CartService'
        public: false

    Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface:
        alias: 'session.flash_bag'
        public: false

    ShoppingCartBundle\Service\ProductServiceInterface:
        alias: 'ShoppingCartBundle\Service\ProductService'
        public: false